# Generated by Django 5.2.7 on 2025-10-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(default='movie/images/default.png', upload_to='movie/images/')),
                ('url', models.URLField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
